//! Go sim/common/classic: items_armor.go, items_store_gaps.go and items_trinkets.go, the classic
//! items the shared package registers by hand. The weapons and enchants of the package
//! (items_weapons.go, enchants.go, emerald_dragon_whelp.go) are ported with the weapon procs.

use std::rc::Rc;

use crate::contracts::prepared_v2::ActionId;

use super::aura_helpers::{CallbackMask, HitOutcome, ProcTrigger};
use super::character::{cooldown_type, MajorCooldown};
use super::env::Environment;
use super::shared_items::dynamic_legacy_proc_for_weapon;
use super::shared_procs::{
    apply_proc_damage_effect, apply_proc_stat_bonus_effect, ProcDamageEffect, ProcStatBonusEffect,
    TriggerDpmFn,
};
use super::sim::{AuraConfig, Cooldown, SECOND};
use super::spell::{school, CastConfig, DefenseType, ProcMask, Resource, SpellConfig, SpellFlag};
use super::spell_mod::{SpellModConfig, SpellModType};
use super::Refusal;

/// The classic package's `core.NewItemEffect` calls this module implements.
pub(crate) fn apply_item_effect(env: &mut Environment, item: i32) -> Result<bool, Refusal> {
    match item {
        18168 => force_reactive_disk(env),
        11669 => damage_shield(env, "Naglering", 11669, 15438, school::ARCANE, 3.0),
        17066 => damage_shield(env, "Drillborer Disk", 17066, 15438, school::ARCANE, 3.0),
        18326 => damage_shield(env, "Razor Gauntlets", 18326, 1302193, school::NATURE, 7.0),
        18815 => damage_shield(
            env,
            "Essence of the Pure Flame",
            18815,
            23266,
            school::FIRE,
            13.0,
        ),
        13959 => omokks_girth_restrainer(env),
        942 => freezing_band(env),
        13952 => melee_frost_proc(env, "Iceblade Hacker", 13952, 1298414, 40.70000076293945),
        13982 => melee_frost_proc(
            env,
            "Warblade of Caer Darrow",
            13982,
            1298499,
            27.719999313354492,
        ),
        14557 => lion_horn(env),
        11819 => second_wind(env),
        11832 => burst_of_knowledge(env),
        19287 => darkmoon_card_heroism(env),
        19289 => darkmoon_card_maelstrom(env),
        22321 => heart_of_wyrmthalak(env),
        _ => return Ok(false),
    }
    Ok(true)
}

/// The item IDs this module registers, for the test against Go's registered IDs.
#[cfg(test)]
pub(crate) const ITEMS: [i32; 15] = [
    18168, 11669, 17066, 18326, 18815, 13959, 942, 13952, 13982, 14557, 11819, 11832, 19287, 19289,
    22321,
];

/// Go `newDamageShieldEffect`: a damage shield: "When struck in combat inflicts damage to the
/// attacker", off every melee hit the wearer takes. The damage neither crits nor partially
/// resists.
fn damage_shield(
    env: &mut Environment,
    name: &str,
    item_id: i32,
    spell_id: i32,
    spell_school: u8,
    damage: f64,
) {
    apply_proc_damage_effect(
        env,
        &ProcDamageEffect {
            item_id,
            spell_id,
            school: spell_school,
            defense_type: DefenseType::Magic,
            min_dmg: damage,
            max_dmg: damage,
            flags: SpellFlag::BINARY
                | SpellFlag::NO_ON_CAST_COMPLETE
                | SpellFlag::PASSIVE_SPELL
                | SpellFlag::PROC,
            trigger: ProcTrigger {
                name: name.to_string(),
                callback: CallbackMask::ON_SPELL_HIT_TAKEN,
                proc_mask: ProcMask::MELEE,
                outcome: HitOutcome::LANDED,
                ..ProcTrigger::default()
            },
            ..ProcDamageEffect::default()
        },
    );
}

/// Force Reactive Disk: an area hit of 25 off every melee attack the wearer blocks, once a
/// second.
fn force_reactive_disk(env: &mut Environment) {
    let unit = env.player;
    env.sim.register_spell(
        unit,
        SpellConfig {
            action_id: ActionId::item(18168),
            spell_school: school::NATURE,
            defense_type: DefenseType::Magic,
            proc_mask: ProcMask::EMPTY,
            flags: SpellFlag::NO_ON_CAST_COMPLETE | SpellFlag::PASSIVE_SPELL,
            damage_multiplier: 1.0,
            threat_multiplier: 1.0,
            ..SpellConfig::default()
        },
    );
    env.sim.make_proc_trigger_aura(
        unit,
        &ProcTrigger {
            name: "Force Reactive Disk".to_string(),
            proc_mask: ProcMask::MELEE,
            icd: SECOND,
            outcome: HitOutcome::BLOCK,
            callback: CallbackMask::ON_SPELL_HIT_TAKEN,
            ..ProcTrigger::default()
        },
    );
}

/// Omokk's Girth Restrainer: equip: decreases all threat generated by 1% (1298501).
fn omokks_girth_restrainer(env: &mut Environment) {
    use super::aura_helpers::PseudoStatField;
    let unit = env.player;
    let aura = env.sim.register_aura(
        unit,
        AuraConfig {
            label: "Omokk's Girth Restrainer".to_string(),
            action_id: Some(ActionId::item(13959)),
            ..AuraConfig::default()
        },
    );
    let aura = env.sim.make_permanent(aura);
    env.sim
        .attach_multiplicative_pseudo_stat_buff(aura, PseudoStatField::ThreatMultiplier, 0.99);
}

/// Freezing Band: when struck in combat has a 1% chance of inflicting 50 Frost damage to the
/// attacker and freezing them for 5s (18798).
fn freezing_band(env: &mut Environment) {
    apply_proc_damage_effect(
        env,
        &ProcDamageEffect {
            item_id: 942,
            spell_id: 18798,
            school: school::FROST,
            defense_type: DefenseType::Magic,
            min_dmg: 50.0,
            max_dmg: 50.0,
            flags: SpellFlag::NO_ON_CAST_COMPLETE
                | SpellFlag::PASSIVE_SPELL
                | SpellFlag::NO_ON_DAMAGE_DEALT
                | SpellFlag::PROC,
            trigger: ProcTrigger {
                name: "Freezing Band".to_string(),
                action_id: ActionId::item(942),
                callback: CallbackMask::ON_SPELL_HIT_TAKEN,
                proc_mask: ProcMask::MELEE,
                outcome: HitOutcome::LANDED,
                require_damage_dealt: true,
                proc_chance: 0.01,
                ..ProcTrigger::default()
            },
            ..ProcDamageEffect::default()
        },
    );
}

/// Iceblade Hacker and Warblade of Caer Darrow: melee attacks with this weapon deal Frost
/// damage, only on the hand holding it, like every generated weapon proc.
fn melee_frost_proc(env: &mut Environment, name: &str, item_id: i32, spell_id: i32, damage: f64) {
    let trigger_dpm: TriggerDpmFn =
        Rc::new(move |sim, unit| dynamic_legacy_proc_for_weapon(sim, unit, item_id, 0.0, 1.0));
    apply_proc_damage_effect(
        env,
        &ProcDamageEffect {
            item_id,
            spell_id,
            school: school::FROST,
            defense_type: DefenseType::Melee,
            min_dmg: damage,
            max_dmg: damage,
            flags: SpellFlag::NO_ON_CAST_COMPLETE
                | SpellFlag::PASSIVE_SPELL
                | SpellFlag::NO_ON_DAMAGE_DEALT
                | SpellFlag::PROC
                | SpellFlag::SUPPRESS_WEAPON_PROCS,
            trigger: ProcTrigger {
                name: name.to_string(),
                action_id: ActionId::item(item_id),
                callback: CallbackMask::ON_SPELL_HIT_DEALT,
                proc_mask: ProcMask::MELEE,
                outcome: HitOutcome::LANDED,
                require_damage_dealt: true,
                proc_chance: 1.0,
                ..ProcTrigger::default()
            },
            trigger_dpm: Some(trigger_dpm),
            ..ProcDamageEffect::default()
        },
    );
}

/// The Lion Horn of Stormwind: when struck in combat has a 5% chance of increasing all party
/// member's armor by 725 for 30s, through the item database's effect entry.
fn lion_horn(env: &mut Environment) {
    apply_proc_stat_bonus_effect(
        env,
        &ProcStatBonusEffect {
            name: "The Lion Horn of Stormwind",
            item_id: 14557,
            callback: CallbackMask::ON_SPELL_HIT_TAKEN,
            proc_mask: ProcMask::MELEE,
            outcome: HitOutcome::LANDED,
            require_damage_dealt: true,
            ..ProcStatBonusEffect::default()
        },
    );
}

/// A use spell on the item's own cooldown and the shared category (2554) Second Wind and Burst
/// of Knowledge sit in.
fn mana_item_spell(env: &mut Environment, item_id: i32, cooldown: i64) -> super::sim::SpellId {
    let unit = env.player;
    let timer = env.sim.new_timer(unit);
    let category = env.sim.category_timer(unit, 2554);
    env.sim.register_spell(
        unit,
        SpellConfig {
            action_id: ActionId::item(item_id),
            proc_mask: ProcMask::EMPTY,
            flags: SpellFlag::NO_ON_CAST_COMPLETE,
            cast: CastConfig {
                cd: Cooldown {
                    timer: Some(timer),
                    duration: cooldown,
                },
                shared_cd: Cooldown {
                    timer: Some(category),
                    duration: 10 * SECOND,
                },
                ..CastConfig::default()
            },
            ..SpellConfig::default()
        },
    )
}

fn add_mana_cooldown(env: &mut Environment, spell: super::sim::SpellId) {
    let unit = env.player;
    env.sim.add_major_cooldown(
        unit,
        MajorCooldown {
            spell,
            priority: 0,
            cooldown_type: cooldown_type::MANA,
            allow_spell_queueing: false,
            timings: Vec::new(),
        },
    );
}

/// Second Wind: use: restores 63 mana every 1 sec for 10 sec (15604). 15 min cooldown, and 10 sec
/// on the category it shares with Burst of Knowledge.
fn second_wind(env: &mut Environment) {
    if !env.sim.has_mana_bar(env.player) {
        return;
    }
    let spell = mana_item_spell(env, 11819, 15 * 60 * SECOND);
    add_mana_cooldown(env, spell);
}

/// Burst of Knowledge: use: reduces the mana cost of all spells by 150 for 10 sec (15646). The
/// client's school mask (126) leaves out Physical.
fn burst_of_knowledge(env: &mut Environment) {
    let unit = env.player;
    if !env.sim.has_mana_bar(unit) {
        return;
    }
    let aura = env.sim.register_aura(
        unit,
        AuraConfig {
            label: "Burst of Knowledge".to_string(),
            action_id: Some(ActionId::item(11832)),
            duration: 10 * SECOND,
            ..AuraConfig::default()
        },
    );
    env.sim.attach_spell_mod(
        aura,
        SpellModConfig {
            kind: SpellModType::PowerCostFlat,
            school: 126,
            resource_type: Some(Resource::Mana),
            int_value: -150,
            ..SpellModConfig::default()
        },
    );
    let spell = mana_item_spell(env, 11832, 6 * 60 * SECOND);
    add_mana_cooldown(env, spell);
}

/// Darkmoon Card: Heroism: equip: sometimes heals bearer of 120 to 180 damage when damaging an
/// enemy in melee (23682). The rate is master's PPM.
fn darkmoon_card_heroism(env: &mut Environment) {
    let unit = env.player;
    let dpm = Rc::new(env.sim.new_ppm_manager(unit, 2.0, ProcMask::MELEE));
    env.sim.make_proc_trigger_aura(
        unit,
        &ProcTrigger {
            name: "Darkmoon Card: Heroism".to_string(),
            action_id: ActionId::item(19287),
            callback: CallbackMask::ON_SPELL_HIT_DEALT,
            proc_mask: ProcMask::MELEE,
            outcome: HitOutcome::LANDED,
            dpm: Some(dpm),
            ..ProcTrigger::default()
        },
    );
}

/// Darkmoon Card: Maelstrom: equip: chance to strike your melee target with lightning for 200 to
/// 300 Nature damage (23687).
fn darkmoon_card_maelstrom(env: &mut Environment) {
    let trigger_dpm: TriggerDpmFn =
        Rc::new(|sim, unit| Rc::new(sim.new_ppm_manager(unit, 1.0, ProcMask::MELEE)));
    apply_proc_damage_effect(
        env,
        &ProcDamageEffect {
            item_id: 19289,
            spell_id: 23687,
            school: school::NATURE,
            defense_type: DefenseType::Magic,
            min_dmg: 200.0,
            max_dmg: 300.0,
            flags: SpellFlag::NO_ON_CAST_COMPLETE | SpellFlag::PASSIVE_SPELL | SpellFlag::PROC,
            trigger: ProcTrigger {
                name: "Darkmoon Card: Maelstrom".to_string(),
                callback: CallbackMask::ON_SPELL_HIT_DEALT,
                proc_mask: ProcMask::MELEE,
                outcome: HitOutcome::LANDED,
                ..ProcTrigger::default()
            },
            trigger_dpm: Some(trigger_dpm),
            ..ProcDamageEffect::default()
        },
    );
}

/// Heart of Wyrmthalak: equip: melee and ranged attacks have a chance to deal 112 to 168 Fire
/// damage (27655). The 0.4 PPM is master's.
fn heart_of_wyrmthalak(env: &mut Environment) {
    let trigger_dpm: TriggerDpmFn =
        Rc::new(|sim, unit| Rc::new(sim.new_ppm_manager(unit, 0.4, ProcMask::MELEE_OR_RANGED)));
    apply_proc_damage_effect(
        env,
        &ProcDamageEffect {
            item_id: 22321,
            spell_id: 27655,
            school: school::FIRE,
            defense_type: DefenseType::Magic,
            min_dmg: 112.0,
            max_dmg: 168.0,
            flags: SpellFlag::NO_ON_CAST_COMPLETE | SpellFlag::PASSIVE_SPELL | SpellFlag::PROC,
            trigger: ProcTrigger {
                name: "Heart of Wyrmthalak".to_string(),
                callback: CallbackMask::ON_SPELL_HIT_DEALT,
                proc_mask: ProcMask::MELEE_OR_RANGED,
                outcome: HitOutcome::LANDED,
                ..ProcTrigger::default()
            },
            trigger_dpm: Some(trigger_dpm),
            ..ProcDamageEffect::default()
        },
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prepare::item_test_support::{aura, environment, spell};
    use crate::prepare::sim::NEVER_EXPIRES;

    #[test]
    fn every_item_is_one_go_registers() {
        let tables = crate::data::tables::tables();
        for item in ITEMS {
            assert!(
                tables.item_effect_ids.contains(&item),
                "item {item} is not registered by Go"
            );
        }
    }

    #[test]
    fn a_damage_shield_listens_to_melee_hits_taken_and_casts_its_spell() {
        // Naglering: 3 Arcane damage to the attacker off every melee hit the wearer takes.
        let env = environment(&[(11669, 0)]);
        let id = aura(&env, "Naglering");
        let shield = env.sim.aura(id);
        assert_eq!(shield.action_id_for_proc, Some(ActionId::item(11669)));
        assert_eq!(
            shield.callback_names(),
            vec!["on_reset", "on_spell_hit_taken"]
        );
        let spell = env.sim.spell(spell(&env, &ActionId::spell(15438)));
        assert_eq!(spell.spell_school, school::ARCANE);
        assert_eq!(spell.defense_type, DefenseType::Magic);
        assert!(spell.flags.matches(SpellFlag::BINARY | SpellFlag::PROC));
    }

    #[test]
    fn omokks_girth_restrainer_lowers_threat_by_one_percent() {
        let env = environment(&[(13959, 0)]);
        let id = aura(&env, "Omokk's Girth Restrainer");
        assert!(env.sim.aura(id).active);
        assert_eq!(env.sim.aura(id).duration, NEVER_EXPIRES);
        assert_eq!(
            env.sim.unit(env.player).pseudo_stats.threat_multiplier,
            0.99
        );
    }

    #[test]
    fn an_iceblade_rolls_only_on_the_hand_that_holds_it() {
        // Iceblade Hacker: a fixed chance of 1 on the main hand it is wielded in.
        let env = environment(&[(13952, 0)]);
        let trigger = env.sim.aura(aura(&env, "Iceblade Hacker"));
        let dpm = trigger.dpm.as_ref().expect("a proc manager");
        assert_eq!(dpm.proc_masks, vec![ProcMask::MELEE_MH]);
        assert_eq!(dpm.proc_chances, vec![1.0]);
    }

    #[test]
    fn the_lion_horn_buffs_armor_from_the_item_effect() {
        let env = environment(&[(14557, 0)]);
        let trigger = env.sim.aura(aura(&env, "The Lion Horn of Stormwind"));
        assert_eq!(
            trigger.callback_names(),
            vec!["on_reset", "on_spell_hit_taken"]
        );
        let buff = env.sim.aura(aura(&env, "The Lion Horn of Stormwind Proc"));
        assert_eq!(buff.duration, 30 * SECOND);
        assert_eq!(buff.icd, trigger.icd);
    }
}
