//! The client rows the Warrior builds from: Go `sim/warrior/spell_data_auto_gen.go`, the ladders
//! the Warrior code reads. Generated from the pinned file; the field order is Go's.

use std::sync::OnceLock;

use crate::prepare::spelldata::Ladder;

/// Go `generatedSpellData`.
pub(super) struct SpellData {
    pub anger_management: Ladder,
    pub anticipation: Ladder,
    pub bastion: Ladder,
    pub battle_shout: Ladder,
    pub battle_stance: Ladder,
    pub battle_stance_passive: Ladder,
    pub berserker_rage: Ladder,
    pub berserker_stance: Ladder,
    pub berserker_stance_triggered: Ladder,
    pub berserker_stance_passive: Ladder,
    pub blood_craze: Ladder,
    pub blood_craze_triggered: Ladder,
    pub bloodrage: Ladder,
    pub bloodrage_triggered: Ladder,
    pub bloodthirst: Ladder,
    pub bloodthrill: Ladder,
    pub bloodthrill_triggered: Ladder,
    pub booming_voice: Ladder,
    pub challenging_shout: Ladder,
    pub charge: Ladder,
    pub charge_triggered: Ladder,
    pub charge_rage_bonus_effect: Ladder,
    pub cleave: Ladder,
    pub concussion_blow: Ladder,
    pub cruelty: Ladder,
    pub death_wish: Ladder,
    pub deep_wounds: Ladder,
    pub deep_wounds_triggered: Ladder,
    pub defensive_stance: Ladder,
    pub defensive_stance_triggered: Ladder,
    pub defensive_stance_passive: Ladder,
    pub defensive_stance_passive_triggered: Ladder,
    pub defensive_state: Ladder,
    pub defensive_state_triggered: Ladder,
    pub defiance: Ladder,
    pub deflection: Ladder,
    pub demoralizing_shout: Ladder,
    pub disarm: Ladder,
    pub dual_wield_specialization: Ladder,
    pub enrage: Ladder,
    pub enrage_triggered: Ladder,
    pub execute: Ladder,
    pub execute_triggered: Ladder,
    pub flurry: Ladder,
    pub flurry_triggered: Ladder,
    pub focused_rage: Ladder,
    pub furious_precision: Ladder,
    pub gore_drinker: Ladder,
    pub hamstring: Ladder,
    pub heroic_strike: Ladder,
    pub impale: Ladder,
    pub improved_battle_shout: Ladder,
    pub improved_berserker_rage: Ladder,
    pub improved_bloodrage: Ladder,
    pub improved_challenging_shout: Ladder,
    pub improved_charge: Ladder,
    pub improved_demoralizing_shout: Ladder,
    pub improved_disarm: Ladder,
    pub improved_execute: Ladder,
    pub improved_hamstring: Ladder,
    pub improved_hamstring_triggered: Ladder,
    pub improved_heroic_strike: Ladder,
    pub improved_intercept: Ladder,
    pub improved_intimidating_shout: Ladder,
    pub improved_overpower: Ladder,
    pub improved_pummel: Ladder,
    pub improved_pummel_triggered: Ladder,
    pub improved_rend: Ladder,
    pub improved_revenge: Ladder,
    pub improved_shield_bash: Ladder,
    pub improved_shield_bash_triggered: Ladder,
    pub improved_shield_block: Ladder,
    pub improved_shield_wall: Ladder,
    pub improved_slam: Ladder,
    pub improved_sunder_armor: Ladder,
    pub improved_tactical_mastery: Ladder,
    pub improved_taunt: Ladder,
    pub improved_thunder_clap: Ladder,
    pub intercept: Ladder,
    pub intercept_triggered: Ladder,
    pub intimidating_shout: Ladder,
    pub intimidating_shout_triggered: Ladder,
    pub iron_will: Ladder,
    pub last_stand: Ladder,
    pub last_stand_triggered: Ladder,
    pub lingering_rage: Ladder,
    pub lingering_rage_triggered: Ladder,
    pub long_daze: Ladder,
    pub master_of_defense: Ladder,
    pub master_of_defense_triggered: Ladder,
    pub mocking_blow: Ladder,
    pub mortal_strike: Ladder,
    pub offensive_state: Ladder,
    pub offensive_state_triggered: Ladder,
    pub overpower: Ladder,
    pub piercing_howl: Ladder,
    pub pummel: Ladder,
    pub raging_blows: Ladder,
    pub recklessness: Ladder,
    pub rend: Ladder,
    pub retaliation: Ladder,
    pub retaliation_triggered: Ladder,
    pub revenge: Ladder,
    pub rule_of_rage: Ladder,
    pub shield_bash: Ladder,
    pub shield_block: Ladder,
    pub shield_slam: Ladder,
    pub shield_specialization: Ladder,
    pub shield_specialization_triggered: Ladder,
    pub shield_wall: Ladder,
    pub slam: Ladder,
    pub spearing_strike: Ladder,
    pub sunder_armor: Ladder,
    pub sweeping_strikes: Ladder,
    pub tactical_mastery: Ladder,
    pub tactical_mastery_triggered: Ladder,
    pub taunt: Ladder,
    pub thunder_clap: Ladder,
    pub two_handed_weapon_specialization: Ladder,
    pub unbridled_wrath: Ladder,
    pub unbridled_wrath_triggered: Ladder,
    pub vanguard: Ladder,
    pub victorious_state: Ladder,
    pub victorious_state_triggered: Ladder,
    pub victory_rush: Ladder,
    pub victory_rush_triggered: Ladder,
    pub weaponmaster: Ladder,
    pub whirlwind: Ladder,
}

/// Go `spellData`.
pub(super) fn spell_data() -> &'static SpellData {
    static DATA: OnceLock<SpellData> = OnceLock::new() ;
    DATA.get_or_init(|| SpellData {
        anger_management: Ladder::ranked(&[12296]),
        anticipation: Ladder::talent(12297, 5),
        bastion: Ladder::talent(16538, 5),
        battle_shout: Ladder::ranked(&[6673, 5242, 6192, 11549, 11550, 11551, 25289]),
        battle_stance: Ladder::ranked(&[2457]),
        battle_stance_passive: Ladder::ranked(&[21156]),
        berserker_rage: Ladder::ranked(&[18499]),
        berserker_stance: Ladder::ranked(&[2458]),
        berserker_stance_triggered: Ladder::ranked(&[7381]),
        berserker_stance_passive: Ladder::ranked(&[7381]),
        blood_craze: Ladder::talent(16487, 3),
        blood_craze_triggered: Ladder::ranked(&[16488]),
        bloodrage: Ladder::ranked(&[2687]),
        bloodrage_triggered: Ladder::ranked(&[29131]),
        bloodthirst: Ladder::ranked(&[23881, 23892, 23893, 23894]),
        bloodthrill: Ladder::talent(1289682, 5),
        bloodthrill_triggered: Ladder::ranked(&[1282733, 1289681]),
        booming_voice: Ladder::talent(12321, 5),
        challenging_shout: Ladder::ranked(&[1161]),
        charge: Ladder::ranked(&[100, 6178, 11578]),
        charge_triggered: Ladder::ranked(&[7922]),
        charge_rage_bonus_effect: Ladder::ranked(&[12695, 12696]),
        cleave: Ladder::ranked(&[845, 7369, 11608, 11609, 20569]),
        concussion_blow: Ladder::ranked(&[12809]),
        cruelty: Ladder::talent(12320, 5),
        death_wish: Ladder::ranked(&[12328]),
        deep_wounds: Ladder::talent(12834, 3),
        deep_wounds_triggered: Ladder::ranked(&[12162, 412609]),
        defensive_stance: Ladder::ranked(&[71]),
        defensive_stance_triggered: Ladder::ranked(&[7376, 12792]),
        defensive_stance_passive: Ladder::ranked(&[7376]),
        defensive_stance_passive_triggered: Ladder::ranked(&[12792]),
        defensive_state: Ladder::ranked(&[5301]),
        defensive_state_triggered: Ladder::ranked(&[5302]),
        defiance: Ladder::talent(12792, 3),
        deflection: Ladder::talent(16462, 5),
        demoralizing_shout: Ladder::ranked(&[1160, 6190, 11554, 11555, 11556]),
        disarm: Ladder::ranked(&[676]),
        dual_wield_specialization: Ladder::talent(23584, 5),
        enrage: Ladder::talent(12317, 5),
        enrage_triggered: Ladder::ranked(&[12880]),
        execute: Ladder::ranked(&[5308, 20658, 20660, 20661, 20662]),
        execute_triggered: Ladder::ranked(&[26651]),
        flurry: Ladder::talent(12319, 5),
        flurry_triggered: Ladder::ranked(&[12966]),
        focused_rage: Ladder::talent(29787, 3),
        furious_precision: Ladder::talent(1323963, 3),
        gore_drinker: Ladder::talent(1323967, 2),
        hamstring: Ladder::ranked(&[1715, 7372, 7373]),
        heroic_strike: Ladder::ranked(&[78, 284, 285, 1608, 11564, 11565, 11566, 11567, 25286]),
        impale: Ladder::talent(16493, 2),
        improved_battle_shout: Ladder::ranked(&[12318, 12857, 12858, 12860, 12861]),
        improved_berserker_rage: Ladder::talent(20500, 2),
        improved_bloodrage: Ladder::talent(12301, 2),
        improved_challenging_shout: Ladder::ranked(&[12327, 12886]),
        improved_charge: Ladder::talent(12285, 2),
        improved_demoralizing_shout: Ladder::ranked(&[12324, 12876, 12877, 12878, 12879]),
        improved_disarm: Ladder::talent(12313, 3),
        improved_execute: Ladder::talent(20502, 2),
        improved_hamstring: Ladder::talent(12289, 3),
        improved_hamstring_triggered: Ladder::ranked(&[23694]),
        improved_heroic_strike: Ladder::talent(12282, 3),
        improved_intercept: Ladder::talent(20504, 2),
        improved_intimidating_shout: Ladder::ranked(&[19870, 19871]),
        improved_overpower: Ladder::ranked(&[12290, 12963]),
        improved_pummel: Ladder::ranked(&[12288, 12707, 12708]),
        improved_pummel_triggered: Ladder::ranked(&[12705]),
        improved_rend: Ladder::talent(12286, 3),
        improved_revenge: Ladder::talent(12797, 3),
        improved_shield_bash: Ladder::talent(12311, 2),
        improved_shield_bash_triggered: Ladder::ranked(&[18498]),
        improved_shield_block: Ladder::ranked(&[12945, 12307, 12944]),
        improved_shield_wall: Ladder::talent(12312, 2),
        improved_slam: Ladder::talent(12862, 2),
        improved_sunder_armor: Ladder::talent(12308, 3),
        improved_tactical_mastery: Ladder::talent(12295, 5),
        improved_taunt: Ladder::ranked(&[12302, 12765]),
        improved_thunder_clap: Ladder::talent(12287, 3),
        intercept: Ladder::ranked(&[20252, 20616, 20617]),
        intercept_triggered: Ladder::ranked(&[20253, 20614, 20615]),
        intimidating_shout: Ladder::ranked(&[5246]),
        intimidating_shout_triggered: Ladder::ranked(&[20511]),
        iron_will: Ladder::talent(12962, 5),
        last_stand: Ladder::ranked(&[12975]),
        last_stand_triggered: Ladder::ranked(&[12976]),
        lingering_rage: Ladder::talent(1323964, 5),
        lingering_rage_triggered: Ladder::ranked(&[1323966]),
        long_daze: Ladder::ranked(&[12705]),
        master_of_defense: Ladder::talent(1310316, 2),
        master_of_defense_triggered: Ladder::ranked(&[23602]),
        mocking_blow: Ladder::ranked(&[694, 7400, 7402, 20559, 20560]),
        mortal_strike: Ladder::ranked(&[12294, 21551, 21552, 21553]),
        offensive_state: Ladder::ranked(&[1282735]),
        offensive_state_triggered: Ladder::ranked(&[1282733]),
        overpower: Ladder::ranked(&[7384, 7887, 11584, 11585]),
        piercing_howl: Ladder::ranked(&[12323]),
        pummel: Ladder::ranked(&[6552, 6554]),
        raging_blows: Ladder::talent(1310315, 1),
        recklessness: Ladder::ranked(&[1719]),
        rend: Ladder::ranked(&[772, 6546, 6547, 6548, 11572, 11573, 11574]),
        retaliation: Ladder::ranked(&[20230]),
        retaliation_triggered: Ladder::ranked(&[20240]),
        revenge: Ladder::ranked(&[6572, 6574, 7379, 11600, 11601, 25288]),
        rule_of_rage: Ladder::ranked(&[1322574]),
        shield_bash: Ladder::ranked(&[72, 1671, 1672]),
        shield_block: Ladder::ranked(&[2565]),
        shield_slam: Ladder::ranked(&[23922, 23923, 23924, 23925]),
        shield_specialization: Ladder::talent(12298, 5),
        shield_specialization_triggered: Ladder::ranked(&[1310318]),
        shield_wall: Ladder::ranked(&[871]),
        slam: Ladder::ranked(&[1240193, 1464, 8820, 11604, 11605]),
        spearing_strike: Ladder::ranked(&[1310222]),
        sunder_armor: Ladder::ranked(&[7386, 7405, 8380, 11596, 11597]),
        sweeping_strikes: Ladder::ranked(&[12292]),
        tactical_mastery: Ladder::ranked(&[1310185]),
        tactical_mastery_triggered: Ladder::ranked(&[12295]),
        taunt: Ladder::ranked(&[355]),
        thunder_clap: Ladder::ranked(&[6343, 8198, 8204, 8205, 11580, 11581]),
        two_handed_weapon_specialization: Ladder::talent(12163, 3),
        unbridled_wrath: Ladder::talent(12322, 5),
        unbridled_wrath_triggered: Ladder::ranked(&[12964]),
        vanguard: Ladder::talent(1310317, 1),
        victorious_state: Ladder::ranked(&[402974]),
        victorious_state_triggered: Ladder::ranked(&[402975]),
        victory_rush: Ladder::ranked(&[402927]),
        victory_rush_triggered: Ladder::ranked(&[402975]),
        weaponmaster: Ladder::talent(1290261, 5),
        whirlwind: Ladder::ranked(&[1680]),
    })
}
