syntax = "proto3";
package proto;

option go_package = "./proto";

import "common.proto";

// DO NOT REMOVE THE COMMENTS
// BEGIN GENERATED
// DruidTalents message.
message DruidTalents {
    // Balance
    int32 improved_wrath = 1;
    int32 genesis = 2;
    int32 moonglow = 3;
    int32 improved_moonfire = 4;
    int32 natures_majesty = 5;
    int32 natures_reach = 6;
    int32 improved_entangling_roots = 7;
    bool natures_splendor = 8;
    bool insect_swarm = 9;
    int32 vengeance = 10;
    int32 improved_starfire = 11;
    int32 overgrowth = 12;
    bool natures_grace = 13;
    int32 eclipse = 14;
    int32 moonfury = 15;
    bool moonkin_form = 16;
    // Feral Combat
    int32 ferocity = 17;
    int32 heart_of_the_wild = 18;
    int32 feral_swiftness = 19;
    int32 feral_instinct = 20;
    int32 brutal_impact = 21;
    int32 thick_hide = 22;
    int32 savage_fury = 23;
    bool feral_charge = 24;
    int32 sharpened_claws = 25;
    int32 shredding_attacks = 26;
    bool mangle = 27;
    int32 predatory_strikes = 28;
    int32 primal_fury = 29;
    int32 predatory_instincts = 30;
    bool leader_of_the_pack = 31;
    int32 king_of_the_jungle = 32;
    int32 natural_reaction = 33;
    int32 rend_and_tear = 34;
    bool berserk = 35;
    // Restoration
    int32 natures_focus = 36;
    int32 furor = 37;
    int32 naturalist = 38;
    int32 subtlety = 39;
    int32 natural_shapeshifter = 40;
    int32 reflection = 41;
    int32 gift_of_nature = 42;
    bool gift_of_the_earthmother = 43;
    int32 tranquil_spirit = 44;
    int32 improved_rejuvenation = 45;
    bool swiftmend = 46;
    bool natures_swiftness = 47;
    int32 living_spirit = 48;
    int32 improved_tranquility = 49;
    int32 improved_regrowth = 50;
    bool wild_growth = 51;
}

// END GENERATED

message BalanceDruid {
  message Rotation {
	}

  message Options {
    UnitReference innervate_target = 1;
	float okf_uptime = 2;
  }
  Options options = 3;
}

message FeralDruid {
  message Rotation {
		bool maintain_faerie_fire = 1;
		int32 min_combos_for_rip = 2;
		float max_wait_time = 3;
		float preroar_duration = 4;
		bool precast_tigers_fury = 5;
		bool use_shred_trick = 6;
  }
	Rotation rotation = 1;

  message Options {
    UnitReference innervate_target = 1;
    int32 latency_ms = 2;
    bool assume_bleed_active = 4;
  }
  Options options = 3;
}

message FeralTankDruid {
  message Rotation {
		// Minimum rage to queue HS or Cleave.
		int32 maul_rage_threshold = 1;
		bool maintain_demoralizing_roar = 2;
		double lacerate_time = 3;
  }

  message Options {
    UnitReference innervate_target = 1;
		double starting_rage = 2;
  }
  Options options = 3;
}

message RestorationDruid {
  message Rotation {
  }

  message Options {
    UnitReference innervate_target = 1;
  }
  Options options = 3;
}
