syntax = "proto3";
package proto;

option go_package = "./proto";

// DO NOT REMOVE THE COMMENTS
// BEGIN GENERATED
// WarlockTalents message.
message WarlockTalents {
    // Affliction
    int32 improved_life_tap = 1;
    int32 suppression = 2;
    int32 improved_corruption = 3;
    int32 malediction = 4;
    int32 soul_harvesting = 5;
    int32 improved_drains = 6;
    int32 improved_bane_of_agony = 7;
    int32 fel_concentration = 8;
    bool amplify_curse = 9;
    int32 pandemic = 10;
    int32 malevolence = 11;
    int32 nightfall = 12;
    bool curse_of_exhaustion = 13;
    bool siphon_life = 14;
    int32 soul_siphon = 15;
    int32 shadow_mastery = 16;
    bool wrack = 17;
    // Demonology
    int32 improved_health_funnel = 18;
    int32 improved_imp = 19;
    int32 demonic_embrace = 20;
    int32 unholy_power = 21;
    int32 demonic_aegis = 22;
    int32 improved_voidwalker = 23;
    int32 fel_vitality = 24;
    int32 demonic_energies = 25;
    int32 improved_sayaad = 26;
    bool demonic_sacrifice = 27;
    int32 master_summoner = 28;
    int32 decimation = 29;
    bool fel_domination = 30;
    int32 demonic_brand = 31;
    int32 improved_felhunter = 32;
    bool soul_link = 33;
    int32 demonic_knowledge = 34;
    int32 master_demonologist = 35;
    bool demonic_pact = 36;
    // Destruction
    int32 destructive_reach = 37;
    int32 improved_shadow_bolt = 38;
    int32 bane = 39;
    int32 molten_skin = 40;
    int32 cataclysm = 41;
    int32 aftermath = 42;
    int32 ruin = 43;
    bool shadowburn = 44;
    int32 intensity = 45;
    int32 agonizing_flames = 46;
    bool conflagrate = 47;
    int32 pyroclasm = 48;
    bool bane_of_havoc = 49;
    int32 fire_and_brimstone = 50;
    int32 shadow_and_flame = 51;
    bool incinerate = 52;
}

// END GENERATED
message WarlockRotation {
}

message WarlockOptions {
	enum Summon {
		NoSummon = 0;
		Imp = 1;
		Voidwalker = 2;
		Succubus = 3;
		Felhunter = 4;
	}

	enum Armor {
		NoArmor = 0;
		DemonArmor = 1;
	}

	enum WeaponImbue {
		NoWeaponImbue = 0;
		Spellstone = 1;
		Firestone = 2;
	}

	enum MaxFireboltRank {
		NoMaximum = 0;
		Rank1 = 1;
		Rank2 = 2;
		Rank3 = 3;
		Rank4 = 4;
		Rank5 = 5;
		Rank6 = 6;
		Rank7 = 7;
		Rank8 = 8;
	}

	Armor armor = 1;
	Summon summon = 2;
	WeaponImbue weapon_imbue = 3;
	MaxFireboltRank max_firebolt_rank = 4;
	bool pet_pool_mana = 5;
	// Demon sacrificed before the pull, needs Demonic Pact to be used together with a summoned demon.
	Summon sacrifice = 6;
}

message Warlock {
	WarlockOptions options = 2;
}

message TankWarlock {
	WarlockOptions options = 2;
}
