//! The Paladin's abilities: Go `forbearance.go`, `righteous_fury.go`, `judgement.go`,
//! `holy_strike.go`, `hammer_of_the_righteous.go`, `consecration.go`, `exorcism.go`,
//! `hammer_of_wrath.go` and `holy_wrath.go`.

use crate::prepare::aura_helpers::{CallbackMask, HitOutcome, ProcTrigger};
use crate::prepare::character::constants::MAX_MELEE_RANGE;
use crate::prepare::dbcenums;
use crate::prepare::sim::{AuraConfig, Sim, UnitId, NEVER_EXPIRES};
use crate::prepare::spell::{
    school, Cast, CastConfig, DotConfig, ProcMask, SpellConfig, SpellFlag,
};
use crate::prepare::spell_mod::{SpellModConfig, SpellModType};
use crate::prepare::spelldata::Spell as Row;

use super::masks;
use super::spell_data::spell_data;
use super::util::{cooldown, gcd_cast, mana_cost, shared_timer, spell_action};
use super::Paladin;

impl Paladin {
    /// Go `registerForbearance`: Cannot be made invulnerable by Divine Shield, Divine
    /// Protection, Blessing of Protection, or shielded by Templar's Bulwark.
    pub(super) fn register_forbearance(&mut self, sim: &mut Sim, unit: UnitId) {
        let rank = spell_data().templars_bulwark_triggered.highest();
        let aura = sim.register_aura(
            unit,
            AuraConfig {
                label: "Forbearance".to_string(),
                action_id: Some(spell_action(rank.id)),
                duration: rank.duration().wrapping_sub(self.forbearance_reduction),
                ..AuraConfig::default()
            },
        );
        self.forbearance = Some(aura);
    }

    /// Go `registerRighteousFury`: increases the threat generated by your Holy attacks by 60%.
    pub(super) fn register_righteous_fury(&mut self, sim: &mut Sim, unit: UnitId) {
        let rank = spell_data().righteous_fury.highest();
        let action_id = spell_action(rank.id);

        let aura = sim.register_aura(
            unit,
            AuraConfig {
                label: "Righteous Fury".to_string(),
                action_id: Some(action_id.clone()),
                duration: NEVER_EXPIRES,
                ..AuraConfig::default()
            },
        );
        sim.attach_spell_mod(
            aura,
            SpellModConfig {
                kind: SpellModType::ThreatMultiplierPct,
                school: school::HOLY,
                float_value: rank.effect(dbcenums::A_MOD_THREAT, 2).percent(),
                ..SpellModConfig::default()
            },
        );
        self.righteous_fury_aura = Some(aura);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id,
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::EMPTY,
                flags: SpellFlag::APL | SpellFlag::HELPFUL,
                class_spell_mask: masks::RIGHTEOUS_FURY,
                cost: mana_cost(rank),
                cast: gcd_cast(rank.gcd(), 0, None),
                related_self_buff: Some(aura),
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerJudgement`: unleash the energy of a Seal spell upon an enemy. The spell
    /// itself has no defense type and rolls nothing: the seal's own judgement spell carries
    /// the hit roll and the effect.
    pub(super) fn register_judgement(&mut self, sim: &mut Sim, unit: UnitId) {
        let rank = spell_data().judgement.highest();
        let timer = shared_timer(sim, unit, &mut self.timers.judgement);

        // No SpellFlagNoOnCastComplete: Sanctified Judgement and Swift Judgement listen for
        // the cast through OnCastComplete, and the flag silences both.
        let spell = sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::EMPTY,
                flags: SpellFlag::APL | SpellFlag::PASSIVE_SPELL,
                class_spell_mask: masks::JUDGEMENT,
                max_range: f64::from(rank.max_range),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                cost: mana_cost(rank),
                cast: CastConfig {
                    // Off the global cooldown, as the client states.
                    default_cast: Cast {
                        non_empty: true,
                        ..Cast::default()
                    },
                    cd: crate::prepare::sim::Cooldown {
                        timer: Some(timer),
                        duration: cooldown(rank),
                    },
                    ..CastConfig::default()
                },
                has_extra_cast_condition: true,
                ..SpellConfig::default()
            },
        );
        self.judgement = Some(spell);

        // Every melee strike that lands refreshes the judgement debuffs on its target.
        let label = sim.unit(unit).label.clone();
        sim.make_proc_trigger_aura(
            unit,
            &ProcTrigger {
                name: format!("Judgement Refresh{label}"),
                callback: CallbackMask::ON_SPELL_HIT_DEALT,
                proc_mask: ProcMask::MELEE,
                outcome: HitOutcome::LANDED,
                trigger_immediately: true,
                ..ProcTrigger::default()
            },
        );
    }

    /// Go `registerHolyStrike`: an instant strike that causes 50% weapon damage plus an
    /// additional 93 as Holy damage.
    pub(super) fn register_holy_strike(&mut self, sim: &mut Sim, unit: UnitId, rank: &Row) {
        let flat = rank.damage_effect();
        let timer = shared_timer(sim, unit, &mut self.timers.holy_strike);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::MELEE_MH_SPECIAL,
                flags: SpellFlag::MELEE_METRICS | SpellFlag::APL,
                class_spell_mask: masks::HOLY_STRIKE,
                rank: rank.rank_number(),
                max_range: MAX_MELEE_RANGE,
                cost: mana_cost(rank),
                // Client cooldown category 2404 holds Holy Strike and Hammer of the
                // Righteous.
                cast: gcd_cast(rank.gcd(), 0, Some((timer, cooldown(rank)))),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                bonus_coefficient: flat.coeff(),
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerHammerOfTheRighteous`: hammer the current target and up to 3 additional
    /// nearby targets, causing Holy damage equal to 3 times your main hand weapon's damage per
    /// second.
    pub(super) fn register_hammer_of_the_righteous(&mut self, sim: &mut Sim, unit: UnitId) {
        let rank = spell_data().hammer_of_the_righteous.highest();
        let timer = shared_timer(sim, unit, &mut self.timers.holy_strike);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::MELEE_MH_SPECIAL,
                flags: SpellFlag::MELEE_METRICS | SpellFlag::APL,
                class_spell_mask: masks::HAMMER_OF_THE_RIGHTEOUS,
                max_range: MAX_MELEE_RANGE,
                cost: mana_cost(rank),
                cast: gcd_cast(rank.gcd(), 0, Some((timer, cooldown(rank)))),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerConsecration`: consecrates the land beneath the Paladin, doing X Holy
    /// damage over 8 sec to enemies who enter the area.
    pub(super) fn register_consecration(
        &mut self,
        sim: &mut Sim,
        unit: UnitId,
        n: i32,
        rank: &Row,
    ) {
        let tick_spell = spell_data().consecration_triggered.rank(n);
        let tick = tick_spell.effect_n(1);

        let dummy = rank.effect(dbcenums::A_PERIODIC_DUMMY, 0);
        let tick_length = dummy.period();
        let number_of_ticks = (rank.duration() / tick_length) as i32;

        let timer = shared_timer(sim, unit, &mut self.timers.consecration);
        let label = sim.unit(unit).label.clone();
        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::SPELL_DAMAGE,
                flags: SpellFlag::APL,
                class_spell_mask: masks::CONSECRATION,
                rank: rank.rank_number(),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                max_range: 8.0,
                cost: mana_cost(rank),
                cast: gcd_cast(rank.gcd(), 0, Some((timer, cooldown(rank)))),
                dot: DotConfig {
                    is_aoe: true,
                    aura: AuraConfig {
                        action_id: Some(spell_action(rank.id)),
                        label: format!("Consecration{label} Rank {}", rank.rank_number()),
                        ..AuraConfig::default()
                    },
                    // The client ticks on a 1 sec period with no tick-on-apply attribute, so
                    // the first tick lands 1 sec in, as on master.
                    number_of_ticks,
                    tick_length,
                    bonus_coefficient: tick.coeff(),
                    ..DotConfig::default()
                },
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerExorcism`: causes 502 Holy damage to an Undead or Demon target.
    pub(super) fn register_exorcism(&mut self, sim: &mut Sim, unit: UnitId, rank: &Row) {
        let damage = rank.damage_effect();
        let timer = shared_timer(sim, unit, &mut self.timers.exorcism);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::SPELL_DAMAGE,
                flags: SpellFlag::APL,
                class_spell_mask: masks::EXORCISM,
                rank: rank.rank_number(),
                max_range: f64::from(rank.max_range),
                cost: mana_cost(rank),
                cast: gcd_cast(rank.gcd(), 0, Some((timer, cooldown(rank)))),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                bonus_coefficient: damage.coeff(),
                has_extra_cast_condition: true,
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerHammerOfWrath`: hurls a hammer that strikes an enemy for 498 Holy damage.
    /// Only usable on enemies that have 20% or less health.
    pub(super) fn register_hammer_of_wrath(&mut self, sim: &mut Sim, unit: UnitId, rank: &Row) {
        let damage = rank.damage_effect();
        let timer = shared_timer(sim, unit, &mut self.timers.hammer_of_wrath);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::RANGED_SPECIAL,
                flags: SpellFlag::APL,
                class_spell_mask: masks::HAMMER_OF_WRATH,
                rank: rank.rank_number(),
                max_range: f64::from(rank.max_range),
                missile_speed: f64::from(rank.speed),
                cost: mana_cost(rank),
                cast: CastConfig {
                    // The client's 1s GCD sits at core's floor, so it is named as the floor
                    // too or GCDTime clamps it.
                    default_cast: Cast {
                        gcd_min: rank.gcd(),
                        gcd: rank.gcd(),
                        cast_time: rank.cast_time(),
                        ..Cast::default()
                    },
                    cd: crate::prepare::sim::Cooldown {
                        timer: Some(timer),
                        duration: cooldown(rank),
                    },
                    ..CastConfig::default()
                },
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                bonus_coefficient: damage.coeff(),
                has_extra_cast_condition: true,
                ..SpellConfig::default()
            },
        );
    }

    /// Go `registerHolyWrath`: sends bolts of holy power in all directions, causing 533 Holy
    /// damage to all Undead and Demon targets within 20 yds.
    pub(super) fn register_holy_wrath(&mut self, sim: &mut Sim, unit: UnitId, rank: &Row) {
        let damage = rank.damage_effect();
        let timer = shared_timer(sim, unit, &mut self.timers.holy_wrath);

        sim.register_spell(
            unit,
            SpellConfig {
                action_id: spell_action(rank.id),
                spell_school: rank.spell_school(),
                defense_type: rank.defense_type_core(),
                proc_mask: ProcMask::SPELL_DAMAGE,
                flags: SpellFlag::APL,
                class_spell_mask: masks::HOLY_WRATH,
                rank: rank.rank_number(),
                max_range: 20.0,
                missile_speed: f64::from(rank.speed),
                cost: mana_cost(rank),
                cast: gcd_cast(rank.gcd(), rank.cast_time(), Some((timer, cooldown(rank)))),
                damage_multiplier: 1.0,
                threat_multiplier: 1.0,
                bonus_coefficient: damage.coeff(),
                ..SpellConfig::default()
            },
        );
    }
}
