#!/usr/bin/env python3
"""Render the ordered contributor board (issue #25) from issue state and validation records.

The board lists every open issue except the board itself:

- one section per milestone, in milestone order, and Maintenance for issues without one;
- within a section, by priority label, then issue number;
- "after #N" for each issue a "Depends on" section names that is still open;
- the status a contributor last gave in an issue comment whose first line starts with
  "Status:", else "in progress" while the issue carries the `claimed` label.

Issues closed in the last two weeks stay in their section, ticked. It ends with the refusal reasons of validation/ records that no issue, open or closed, states
as its "Reason today", so new gaps surface as candidates for an issue.

    python3 tools/board.py render [--issues FILE]   # print the board
    python3 tools/board.py check [--issues FILE]    # fail if issue #25 differs
    python3 tools/board.py update                   # write the board to issue #25

Without --issues the issues come from `gh issue list`; FILE holds the same JSON. Uses Python's
standard library and the GitHub CLI.
"""

import argparse
from datetime import datetime, timedelta, timezone
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parent.parent
REPOSITORY = "sage3648/mythicsim-forever-engine"
BOARD = 25
FIELDS = "number,title,state,milestone,labels,body,comments,closedAt"
CANDIDATE_LIMIT = 10
# Closed issues stay on the board, ticked, for this many days.
RECENT_DAYS = 14

HEADER = """This is the ordered list of open work. Take items from the top when you can.
It is generated by `python3 tools/board.py update`; change the issues, not this text.

## How to pick up work

1. Pick an open item below. Items marked `good first issue` are a good start.
2. Comment on the issue to claim it. A maintainer adds the `claimed` label.
3. Keep your status current with an issue comment whose first line starts with `Status:`,
   such as `Status: branch holy-nova-live-healing-power, PR open`. The board shows the latest.
4. If an item says "after #N", finish that item first.
5. Read [CONTRIBUTING.md](https://github.com/sage3648/mythicsim-forever-engine/blob/main/CONTRIBUTING.md) and run its checks before you open a PR.
6. Every mechanics change needs a fixture or test that matches the Go engine.

If you go quiet for two weeks, the item can be given to someone else.
"""

FOOTER = """New gaps come from the validation records. See [docs/validation-summary.md](https://github.com/sage3648/mythicsim-forever-engine/blob/main/docs/validation-summary.md)."""


def gh(*args):
    return subprocess.run(["gh", *args, "--repo", REPOSITORY], capture_output=True, text=True,
                          check=True).stdout


def load_issues(path):
    if path:
        return json.loads(Path(path).read_text())
    return json.loads(gh("issue", "list", "--state", "all", "--limit", "500", "--json", FIELDS))


def labels(issue):
    return {label["name"] for label in issue.get("labels") or []}


def priority(issue):
    for name in labels(issue):
        match = re.match(r"priority: (\d+)", name)
        if match:
            return int(match.group(1))
    return 9


def dependencies(issue):
    """Issue numbers in the body's "Depends on" section."""
    match = re.search(r"^## Depends on\s*\n(.*?)(?=^## |\Z)", issue.get("body") or "", re.M | re.S)
    return [int(number) for number in re.findall(r"#(\d+)", match.group(1))] if match else []


def status(issue):
    """The latest "Status:" comment's first line, or the claimed label."""
    for comment in reversed(issue.get("comments") or []):
        first = (comment.get("body") or "").strip().splitlines()[:1]
        if first and first[0].lower().startswith("status:"):
            return first[0].split(":", 1)[1].strip()
    return "in progress" if "claimed" in labels(issue) else None


def section(issue):
    milestone = issue.get("milestone") or {}
    return milestone.get("title") or "Maintenance"


def section_key(title):
    match = re.match(r"(\d+)\.", title)
    return (0, int(match.group(1)), title) if match else (1, 0, title)


def reason_patterns(issues):
    """Every issue's "Reason today" lines as patterns: <...> placeholders and numbers vary."""
    patterns = []
    for issue in issues:
        for reason in re.findall(r"^Reason today:\s*`(.+?)`\s*$", issue.get("body") or "", re.M):
            pattern = ""
            for part in re.split(r"(<[^>]*>|\d+)", reason):
                if part.startswith("<") and part.endswith(">"):
                    pattern += ".+"
                elif part.isdigit():
                    pattern += r"\d+"
                else:
                    pattern += re.escape(part)
            patterns.append(re.compile(pattern))
    return patterns


def record_reasons(directory):
    """Refusal reasons the validation records' cases state, with the variants stating them."""
    counts = {}
    for path in sorted(directory.glob("*.json")):
        record = json.loads(path.read_text())
        cases = record.get("cases") if isinstance(record, dict) else None
        for case in cases if isinstance(cases, list) else []:
            if not isinstance(case, dict):
                continue
            reasons = case.get("reasons") or case.get("rejected") or []
            for reason in reasons if isinstance(reasons, list) else []:
                if isinstance(reason, str):
                    counts[reason] = counts.get(reason, 0) + 1
    return counts


def candidates(issues, directory):
    """Record refusals no issue states, grouped with their numbers as N, most variants first."""
    patterns = reason_patterns(issues)
    groups = {}
    for reason, count in record_reasons(directory).items():
        if any(pattern.search(reason) for pattern in patterns):
            continue
        key = re.sub(r"\d+", "N", reason)
        groups[key] = groups.get(key, 0) + count
    return sorted(groups.items(), key=lambda item: (-item[1], item[0]))


def render(issues, directory=ROOT / "validation", now=None):
    cutoff = (now or datetime.now(timezone.utc)) - timedelta(days=RECENT_DAYS)

    def recent(issue):
        return (issue["state"].upper() == "CLOSED" and issue.get("closedAt")
                and datetime.fromisoformat(issue["closedAt"].replace("Z", "+00:00")) >= cutoff)

    listed = [issue for issue in issues if issue["number"] != BOARD
              and (issue["state"].upper() == "OPEN" or recent(issue))]
    open_numbers = {issue["number"] for issue in listed if issue["state"].upper() == "OPEN"}
    sections = {}
    for issue in listed:
        sections.setdefault(section(issue), []).append(issue)
    lines = [HEADER]
    for title in sorted(sections, key=section_key):
        lines.append(f"## {title}\n")
        for issue in sorted(sections[title], key=lambda issue: (priority(issue), issue["number"])):
            if issue["state"].upper() != "OPEN":
                lines.append(f"- [x] #{issue['number']} {issue['title']}")
                continue
            notes = [f"after #{number}" for number in dependencies(issue) if number in open_numbers]
            current = status(issue)
            if current:
                notes.append(f"status: {current}")
            suffix = f" ({'; '.join(notes)})" if notes else ""
            lines.append(f"- [ ] #{issue['number']} {issue['title']}{suffix}")
        lines.append("")
    found = candidates(issues, directory)
    if found:
        lines.append("## Refusals without an issue\n")
        lines.append("Validation records refuse these and no issue states them as its reason today. "
                     "Open an issue before working on one.\n")
        for reason, count in found[:CANDIDATE_LIMIT]:
            lines.append(f"- {count} variants: `{reason}`")
        if len(found) > CANDIDATE_LIMIT:
            lines.append(f"- and {len(found) - CANDIDATE_LIMIT} more")
        lines.append("")
    lines.append(FOOTER)
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=["render", "check", "update"])
    parser.add_argument("--issues", help="JSON of `gh issue list --json " + FIELDS + "`")
    args = parser.parse_args()
    board = render(load_issues(args.issues))
    if args.command == "render":
        sys.stdout.write(board)
    elif args.command == "check":
        current = json.loads(gh("issue", "view", str(BOARD), "--json", "body"))["body"]
        if current.strip() != board.strip():
            sys.exit(f"issue #{BOARD} differs from the rendered board; run python3 tools/board.py update")
        print(f"Issue #{BOARD} is current.")
    else:
        path = ROOT / "output" / "board.md"
        path.parent.mkdir(exist_ok=True)
        path.write_text(board)
        gh("issue", "edit", str(BOARD), "--body-file", str(path))
        print(f"Updated issue #{BOARD}.")


if __name__ == "__main__":
    main()
